### ISSUE TITLE
CSS Themes

### ISSUE THREAD

**Issue by ThornWalli** [GrabarzUndPartner/gp-vue-boilerplate#199]
I have a project that consists of several independent websites and a collection of components. Now you want to use a different styling (theme) for each website, so each component must have its own CSS for each theme.

A style tag can be created for each theme. 

```html
<!-- Theme A -->
<style lang="postcss" theme="theme-a">…</style>

<!-- Theme B -->
<style lang="postcss" theme="theme-b">…</style>
```

An alternative would be to set theme classes on a root element. The class is then used in CSS to select the appropriate selector for the theme.

```css
/* Theme A */
body.theme-a .component-a { … }

/* Theme B */
body.theme-b .component-a { … }
```

**Comment by StephanGerbeth** [comment]
I think this will be helpful
https://medium.com/xebia/theming-in-vue-single-file-components-7b88eaa0eb6e
