### ISSUE TITLE
Nuxt Module i18n is optional and could be switched in config files

### ISSUE THREAD

**Issue by deepsoul** [GrabarzUndPartner/gp-vue-boilerplate#200]
**Is your feature request related to a problem? Please describe.**
Not in every setup you need mulitlingual features. If you include the nuxt i18n module the js-size is much bigger than without. 

**Describe the solution you'd like**
I want to decide in the nuxt config if the project is multilingual or not

**Comment by StephanGerbeth** [comment]
because there is only a minimal client on board we do not need this feature anymore
